### ISSUE TITLE
Fix up the spec reference source

### ISSUE THREAD

**Issue by davefp** [rubygems/guides#119]
The Specification Reference source [specification-reference.md](https://github.com/rubygems/guides/blob/gh-pages/specification-reference.md) is riddled with HTML tags. If I had to guess I'd say that it used to be a generated HTML doc that got semi-converted to Markdown.

Things that can/should have the HTML stripped out of them:

* Plain HTML that would be auto-generated by Markdown (e.g. `<p>`, `<pre>`, etc.)
* Formatted multi-line code samples such as the example Gemfile at the top of the guide
* HTML encoded characters

Things that should be left alone:

* The empty page section anchors

**Comment by arthurnn** [comment]
specification-reference.md is autogen by a rake task, see https://github.com/rubygems/guides/commit/39a52b07f687024edaf48df62019a9c1e21c3041#commitcomment-9755410

**Comment by davefp** [comment]
Ah! That makes sense. Closing.
