### ISSUE TITLE
Broken GemTesters link

### ISSUE THREAD

**Issue by cakejelly** [rubygems/guides#151]
On http://guides.rubygems.org/make-your-own-gem/#writing-tests, the "GemTesters" link is pointing to http://test.rubygems.org/ which seems to be dead or down at the moment

**Comment by dwradcliffe** [comment]
I think that is long gone and should be removed from the guide.

**Comment by bf4** [comment]
Yeah https://github.com/rubygems/gem-testers seems old, 2011... also gem test is dead :boom: https://github.com/rubygems/rubygems-test/issues/36
