### ISSUE TITLE
Unable to locate the malloc method in the extension source code.

### ISSUE THREAD

**Issue by PeterCamilleri** [rubygems/guides#157]
The extconf.rb file looks for methods called "malloc" and "free"

`abort 'missing malloc()' unless have_func 'malloc'`
`abort 'missing free()'   unless have_func 'free'`

Searching the code, it is easy to see where free is defined to Ruby:

`rb_define_method(cMyMalloc, "free", my_malloc_release, 0);`

I have been unable to locate any trace of the malloc method. What am I missing here?

**Comment by segiddins** [comment]
I think those are just making sure you have a C stdlib available to link, but I'm not 100% sure

**Comment by PeterCamilleri** [comment]
I checked and yes, it seems it is just an RTL accessibility check.
Maybe add a comment to that effect.
