### ISSUE TITLE
Document single-digit pessimistic versions

### ISSUE THREAD

**Issue by indirect** [rubygems/guides#159]
As discussed in rubygems/rubygems#1684, while there is API documentation around single-digit pessimistic versions, there is no mention of this behavior or expectation in the guide at http://guides.rubygems.org/patterns/#pessimistic-version-constraint. We should explain!

**Comment by aciccarello** [comment]
Was this closed in #188?

**Comment by bronzdoc** [comment]
Closed by https://github.com/rubygems/guides/pull/188
