### ISSUE TITLE
Broken link in Guide make-your-own-gem

### ISSUE THREAD

**Issue by andrericardo** [rubygems/guides#166]
In  guides/make-your-own-gem.md
"of
[tutorials](https://github.com/seattlerb/minitest/blob/master/README.txt)" link is broken
it moved to https://github.com/seattlerb/minitest/blob/master/README.rdoc

**Comment by dwradcliffe** [comment]
Good catch, feel free to open a pull request! 😃

**Comment by andrericardo** [comment]
@dwradcliffe just sent #167 hope that is the way to do it!
