### ISSUE TITLE
Outdated info in SSL Certificate Update

### ISSUE THREAD

**Issue by altbdoor** [rubygems/guides#168]
In reference to this [page](http://guides.rubygems.org/ssl-certificate-update/), RubyGems.org recently updated their SSL cert, and I find myself with a broken RubyGem. While running through the page for a fix, I found a couple of issues.

- In the **Installing using update packages (NEW)** section, it says to *download the proper version of RubyGems for your installation*, but the links to the 2.2.5 and 2.6.7 release tags do not have any `.gem` file in the release.

- I was already running RubyGems 2.2.5, and the latest RubyGems for 2.2.x is 2.2.5. The guide only mentions that I need to update to the latest 2.2.x, but what is there to update when its already the latest?

- In the **Manual solution to SSL issue** section, the link to the *AddTrustExternalCARoot-2048.pem* is broken. The [RubyGems GitHub](https://github.com/rubygems/rubygems/tree/master/lib/rubygems/ssl_certs) appears to have restructured the `ssl_cert` folder.

- While I did not test it out myself, [several users](https://gist.github.com/luislavena/f064211759ee0f806c88#gistcomment-1893256) report that updating directly to the latest RubyGems solves the issue. Could a description be written down?

[A](http://help.rubygems.org/discussions/problems/22983-ssl-server-certificate-verify-failed) [lot](https://groups.google.com/forum/#!topic/rubygems-org/jcqpXXvOo0c) [of](https://gist.github.com/luislavena/f064211759ee0f806c88) links are referencing to this page, so I think its important to get it up to date.

Regards.

**Comment by sonalkr132** [comment]
Hi @altbdoor Thank you for reporting this :+1:

We have updated [the ssl page](http://guides.rubygems.org/ssl-certificate-update/). Can you please confirm if you are still having any issue updating your rubygem :gem: ?

**Comment by altbdoor** [comment]
Hi @sonalkr132,

Actually I had already updated before opening this issue. Only wanted to help others who hit the guides :) 

From what I can read on the page, the instructions are a lot clearer now. But to futureproof it, you should consider directing visitors to get the gem file from the [downloads page](https://rubygems.org/pages/download), instead of a link to the current 2.6.7 gem file.

Other than that, its perfect right now. Feel free to close the ticket, and thank you very much!

**Comment by sonalkr132** [comment]
>  you should consider directing visitors to get the gem file from the downloads page, instead of a link to the current 2.6.7 gem file.

We are just trying to avoid any unnecessary confusion :smile:
