### ISSUE TITLE
Cleaning up "SSL Certificate Updates" posts

### ISSUE THREAD

**Issue by duckinator** [rubygems/guides#171]
Hi! I'm currently editing the [SSL Certificate Updates](http://guides.rubygems.org/ssl-certificate-update/) post to make it a bit clearer ([my changes](https://github.com/rubygems/guides/compare/gh-pages...duckinator:ssl-guide-editing)).

Is there any actual need for the [Manual Solution To SSL Issue](http://guides.rubygems.org/ssl-certificate-update/#manual-solution-to-ssl-issue) section? As far as I can tell, you should be able to use the [Installing Using Update Packages](http://guides.rubygems.org/ssl-certificate-update/#installing-using-update-packages) section in all cases. Is that not correct?

**Comment by dwradcliffe** [comment]
If you can't upgrade to the latest package for some reason you might need the manual fix. At times in the past the latest version didn't work on windows at all. Not sure if that's the case now or not.

**Comment by indirect** [comment]
Because of the [Globalsign outage](http://www.theregister.co.uk/2016/10/13/globalsigned_off/), many browsers have currently or previously refused to allow downloading the RubyGems 2.6.7 `.gem` file directly. :sob: The manual solution is the worst case last-ditch attempt.

**Comment by duckinator** [comment]
Okay, thanks! That makes it a lot clearer how I should word things.
