### ISSUE TITLE
RubyGems/Bundler guides cross-linking.

### ISSUE THREAD

**Issue by duckinator** [rubygems/guides#173]
Generally, people use Bundler to create gems. While http://guides.rubygems.org/make-your-own-gem/ is still useful to have (so people can understand what exactly it's doing), should it have a note pointing people to https://bundler.io/v1.13/guides/creating_gem.html for most cases?

**Comment by indirect** [comment]
That seems reasonable. 👍

**Comment by duckinator** [comment]
So I'm thinking...

Have the following link to https://bundler.io/v1.13/guides/creating_gem.html:

* http://guides.rubygems.org/what-is-a-gem
* http://guides.rubygems.org/make-your-own-gem

and have https://bundler.io/v1.13/guides/creating_gem.html link to all of:

* http://guides.rubygems.org/gems-with-extensions
* http://guides.rubygems.org/name-your-gem
* http://guides.rubygems.org/security
* http://guides.rubygems.org/patterns

**Comment by duckinator** [comment]
"What is a gem?" links to "Make Your Own Gem", and I figured it having *two* links to guides on how to make a gem would be confusing, so my PR only adds it to "Make Your Own Gem."

https://github.com/rubygems/guides/pull/175

I'll make a PR over on Bundler's website for the other ones.

**Comment by igneus** [comment]
Seems to be all done. Am I missing anything?

**Comment by tnir** [comment]
Ready to close?

**Comment by deivid-rodriguez** [comment]
I guess!
