### ISSUE TITLE
404 error accessing the Specification Reference page

### ISSUE THREAD

**Issue by chocolateboy** [rubygems/guides#205]
The [Specification Reference](http://guides.rubygems.org/specification-reference) page (e.g. [guides.rubygems.org](http://guides.rubygems.org/) → [Specification Reference](http://guides.rubygems.org/specification-reference)) appears to be missing:

<blockquote>
404

File not found

The site configured at this address does not contain the requested file.

If this is your site, make sure that the filename case matches the URL.
For root URLs (like http://example.com/) you must provide an index.html file.

Read the full documentation for more information about using GitHub Pages. 
</blockquote>

I've tried various variations in various browsers e.g.:

* http://guides.rubygems.org/specification-reference
* http://guides.rubygems.org/specification-reference/
* https://guides.rubygems.org/specification-reference
* https://guides.rubygems.org/specification-reference/

**Comment by chocolateboy** [comment]
Not sure if this is related, but there's a typo in the permalink [here](https://github.com/rubygems/guides/blob/c6e1b8baacb9fbbcaf1132a37fde6820570557b5/specification-reference.md):

s/specification-refence/specification-reference/

**Comment by colby-swandale** [comment]
Thanks for reporting this issue, i'm looking into this issue.

**Comment by colby-swandale** [comment]
I've reverted #201 which caused the 404s when coming from Google.com. Thanks again for the report.
