### ISSUE TITLE
Enable HTTPS for guides.rubygems.org

### ISSUE THREAD

**Issue by reedloden** [rubygems/guides#215]
GitHub Pages can do [HTTPS for custom domains](https://blog.github.com/2018-05-01-github-pages-custom-domains-https/) now. Woo!

This means that we can finally have https://guides.rubygems.org/ -- double woo!

Steps to make the magic happen:
1. Update the DNS CNAME entry for `guides.rubygems.org` to be `rubygems.github.io` (may not be necessary, but would be good to do, as per GitHub documentation).
2. Go to https://github.com/rubygems/guides/settings and remove the contents of "Custom domain" box. Click Save.
3. Enter `guides.rubygems.org` back into "Custom domain" box. Click Save.
4. Wait up to one hour for SSL certificate to be generated.
5. Click "Enforce HTTPS" checkbox.

Once that's done, can start updating other places to reference the HTTPS version of the guides site.

**Comment by indirect** [comment]
Done, the guides site is now https://guides.rubygems.org. 👍
