### ISSUE TITLE
command-reference.md - 'Options' parsing - CommonMark issue

### ISSUE THREAD

**Issue by MSP-Greg** [rubygems/guides#233]
I noticed this when I needed to reference:

https://msp-greg.github.io/ruby_trunk/rubygems/file.command-reference.html

I'm using the same md parser as GitHub (commonmarker), while rdoc uses it's own md parser.  Not sure about Jekyll...

Anyway, check the options sections in:
https://github.com/rubygems/guides/blob/gh-pages/command-reference.md
vs:
https://github.com/MSP-Greg/guides/blob/md-commonmark/command-reference.md

The following line:
https://github.com/rubygems/guides/blob/9bf5801a05ad9440a0bb871f902f0d3a31feca10/Rakefile#L129

Changed to:
```ruby
options += "* #{helpline.strip}\n"
```

fixes the issue.

**Comment by bronzdoc** [comment]
Thanks @MSP-Greg! want to submit a PR for it?

**Comment by MSP-Greg** [comment]
@bronzdoc

Ok.  See @234.

Would docs of RubyGems & Bundler masters be helpful?  I always use the copies in Ruby trunk, but it's often behind the respective masters.  Typically, I update once or twice a day...
