### ISSUE TITLE
Minimum `gem` command version for MFA support?

### ISSUE THREAD

**Issue by cben** [rubygems/guides#245]
https://guides.rubygems.org/using-mfa-in-command-line/  
I enabled MFA on my rubygems account, tried "UI and API" level but it failed without prompting me for OTP.  I didn't run `gem push` directly but via gem-release (https://github.com/svenfuchs/gem-release/issues/88), but apparently the problem was simply that my `gem` command was too old.
I got it via `rbenv install 2.5.6`; `gem --version` said 2.7.6.2, and it doesn't support --otp, so I guess doesn't know how to prompt either.
Building ruby 2.6.4 gave me gem 3.0.3 which does support --otp so I guess would Just Work (will confirm next time I release a version).

Anyway, it wasn't obvious from the error message that's my problem.  It'd be nice to update the MFA guide with minumum required version of `gem` and/or minimum version of Ruby it comes with.

**Comment by cben** [comment]
Apperently added in https://github.com/rubygems/rubygems/pull/2369/ so gem ≥ 3.0.0,
merged into ruby ≥ 2.6.0 https://github.com/ruby/ruby/commit/7a46a3b94121339cbead211c4497142bee82fddb ?

**Comment by hsbt** [comment]
MFA feature is only supported by Ruby 2.6+ or RubyGems 3.0+
