### ISSUE TITLE
Remove references to `-rubygems`.

### ISSUE THREAD

**Issue by duckinator** [rubygems/guides#250]
https://guides.rubygems.org/faqs/ mentions `ruby -rubygems` a few times. The `-rubygems` part should be removed, since it's deprecated.

**Comment by lauragift21** [comment]
Hi @duckinator is it okay if I take this on?

**Comment by duckinator** [comment]
@lauragift21 go for it! :+1:

**Comment by lauragift21** [comment]
Awesome thanks!
