### ISSUE TITLE
Deploy guides with universal deploy script

### ISSUE THREAD

**Issue by abitrolly** [rubygems/guides#274]
Fix for #249 requires newer `rdoc` and installing newer `rdoc` is impossible on GitHub Pages, because it doesn't allow that. It is possible to just commit generated static site from Travis https://docs.travis-ci.com/user/deployment-v2/providers/pages/

**Comment by deivid-rodriguez** [comment]
We're no longer using TravisCI and the issue seems fixed anyways, so closing!
