### ISSUE TITLE
GEM BUILD is not correct in command reference on web (even with RubyGems 3.2.19)

### ISSUE THREAD

**Issue by tnir** [rubygems/guides#288]
Even after the fix rubygems/rubygems#4613 (and subsequent rubygems/guides@d7db87d2e5e07dc7d2204355d30d472143d27a4b), we are seeing something wrong at https://guides.rubygems.org/command-reference/:

## as is

![3 2 19](https://user-images.githubusercontent.com/10229505/120258979-02259100-c2ce-11eb-95ae-f67df00eaced.png)

## Expected

![to_be](https://user-images.githubusercontent.com/10229505/120258977-005bcd80-c2ce-11eb-838d-ff8a7a1a582a.png)

**Comment by tnir** [comment]
https://github.com/rubygems/guides/commit/d7db87d2e5e07dc7d2204355d30d472143d27a4b#r51553210

**Comment by simi** [comment]
Seems there is change needed in https://github.com/rubygems/guides/blob/gh-pages/command-reference.erb as well. Most likely somewhere in https://github.com/rubygems/guides/blob/gh-pages/lib/options_list_markdownizer.rb.

**Comment by deivid-rodriguez** [comment]
Yeah, @simi is correct, option parsing needed some tweaking. #290 should fix this.
