### ISSUE TITLE
Rename `gh-pages` to `main` (or `master`)

### ISSUE THREAD

**Issue by hsbt** [rubygems/guides#326]
`gh-pages` seems only deployed branch for github users because it's used by special name in the past. Now, GitHub Pages supports any branch name like `main`, `master` or anything. 

We should rename it to `main` branch. Does anyone have a concern about this?

**Comment by simi** [comment]
If that's that simple (rename branch and update 1 config), let's do that :muscle:.

**Comment by hsbt** [comment]
Thanks! I'll work tomorrow.

**Comment by hsbt** [comment]
done 🎉
