### ISSUE TITLE
Sample .gemrc from "using-s3-source" doc is not working anymore

### ISSUE THREAD

**Issue by pznamensky** [rubygems/guides#343]
It seems there is an error in the doc as this `.gemrc` seems not working anymore:
https://github.com/rubygems/guides/blob/3667c39aea8d5a0a86dac3040020a0bd5e5b2999/using-s3-source.md?plain=1#L57-L84

How to reproduce:
- create `.gemrc` as above
- invoke `gem env`
- you'll see the error:
  ```Failed to load /root/.gemrc, (<unknown>): did not find expected ',' or '}' while parsing a flow mapping at line 8 column 12```
- also in `GEM CONFIGURATION` section there will be no `s3_source` config

Tested with gem 3.4.10 & ruby 3.2.2

**Comment by hsbt** [comment]
@pznamensky Thank you. It may be fixed at #344
