### ISSUE TITLE
Documentation about 'test_files' is confusing

### ISSUE THREAD

**Issue by emilsoman** [rubygems/guides#90]
According to the [section in the guides](https://github.com/rubygems/guides/blob/9f2d1c25639475e8a16b62e776c227ba5439e683/specification-reference.md#test_filesfiles) that talks about `test_files` gemspec attribute, `test_files` is a collection of unit test file which will be loaded as unit tests when the user requests a gem to be unit tested. How does the user request a gem to be unit tested ? Looks like `--test` option was removed from the `gem` command. So how is this `test_files` gemspec attribute useful currently ?

**Comment by postmodern** [comment]
Can we get confirmation from someone on the rubygems team? The lack of confirmation is confusing whether `test_files` will, or wont, or eventually might be deprecated?

**Comment by schmijos** [comment]
> I removed them since they're no longer useful or recommended to set.

@drbrain I'd like to challenge this in one aspect. I often read very old code. Having the test suite distributed by long term archives like [RubyForge](https://web.archive.org/web/20230000000000*/rubyforge.org) or [RubyGems](https://rubygems.org/) **is** useful because the original source often disappeared from the web.

**Comment by postmodern** [comment]
@schmijos older gems will still contain their `test/` or `spec/` files. Going forward, omitting the test files might make it difficult in the future if certain gem's git repositories disappear.

**Comment by simi** [comment]
@schmijos currently `gem` files are intended to keep only runtime files. Test files, configs (like rubocop, ...) and other repo only related files are considered best practice to not be included. It is not intended to preserve whole source code repository in `gem` packages.
